# Site settings
title: Yu-Jen Lin
email: peacedove5210@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/yujenlin" # the subpath of your site, e.g. /blog/
url: "http://peacedove.github.io" # the base hostname & protocol for your site
twitter_username: YujenLin1
github_username:  peacedove

# Build settings
markdown: kramdown
permalink: /:title/
